"""HIT rules from the uploaded PDF, current native DBA and private reports."""
import json,subprocess,unittest
from pathlib import Path
import fitz
from playwright.sync_api import expect
import test_personal_predictions as personal
import test_protected_server as protected
ROOT=Path(__file__).resolve().parents[1]
class HitArithmeticTests(unittest.TestCase):
 def test_pdf_angles_orbs_wrap_and_three_native_hit_types(self):
  script="""require('./vendor/hit/engine.js');const M=KPHitMath,ids=['Su','Mo','Ma','Me','Ju','Ve','Sa','Ra','Ke'],lon=[0,30,90,135,210,270,330,60,240];const model={ready:true,planets:ids.map((id,i)=>({id,longitude:lon[i]*3600,stl:'Sa'})),houses:Array.from({length:12},(_,i)=>({id:i+1,signIndex:i,longitude:i*30*3600}))},periods={ready:true,periods:[{level:'MD',id:'Ma'},{level:'AD',id:'Me'},{level:'PD',id:'Ve'}]};console.log(JSON.stringify({boundary:[M.aspect(0,27),M.aspect(0,33),M.aspect(0,33.001),M.aspect(359,29),M.aspect(0,172),M.aspect(0,171.999)],base:M.analyze(model,periods,{stars:false}),stars:M.analyze(model,periods),only:M.analyze(model,periods,{stars:false,level:'MD',type:'house',kind:'negative'}),dirs:[0,30,60,90,120,150,180,210,240,270,300,330].map(M.direction)}));"""
  d=json.loads(subprocess.run(['node','-e',script],cwd=ROOT,check=True,capture_output=True,text=True).stdout);self.assertEqual(d['boundary'][0]['angle'],30);self.assertEqual(d['boundary'][1]['angle'],30);self.assertIsNone(d['boundary'][2]);self.assertEqual(d['boundary'][3]['distance'],30);self.assertEqual(d['boundary'][4]['angle'],180);self.assertIsNone(d['boundary'][5])
  self.assertEqual({h['type'] for h in d['base']['hits']},{'planet','house','lord'});self.assertTrue(any(h['from']=='Su' and h['active']=='Ma' and h['angle']==90 for h in d['base']['hits']));self.assertTrue(d['only']['hits']);self.assertTrue(all(h['type']=='house' and h['active']=='Ma' and h['kind']=='negative' for h in d['only']['hits']));self.assertTrue(any(h['starPriority'] for h in d['stars']['hits']));self.assertEqual(d['dirs'][0]['zones'],'E4 E5 E6');self.assertEqual(d['dirs'][3]['zones'],'N6 N7');self.assertEqual(d['dirs'][11]['zones'],'E7 E8 S1');self.assertTrue(d['base']['remedies']);self.assertTrue(all(r['items'] and r['deity'] for r in d['base']['remedies']))
class HitInterfaceTests(unittest.TestCase):
 setUpClass=classmethod(personal.PersonalPredictionTests.setUpClass.__func__);tearDownClass=classmethod(personal.PersonalPredictionTests.tearDownClass.__func__);setUp=personal.PersonalPredictionTests.setUp;tearDown=personal.PersonalPredictionTests.tearDown
 def test_compact_icon_current_dba_native_remedies_and_print(self):
  p=self.page;p.wait_for_function('document.getElementById("hit-level")');native=p.evaluate('JSON.stringify(currentKPModel)');western=p.evaluate('KPWesternAspects.getSettings()');p.locator('#quick-hit-theory').click();expect(p.locator('#hit-current')).to_contain_text('MD');data=p.evaluate('KPHit.getData()');self.assertTrue(data['ready']);self.assertTrue(data['hits']);self.assertEqual([r['id'] for r in data['periods']],p.evaluate('KPDashaFal.current().periods.map(p=>p.id)'))
  p.locator('#hit-level').select_option('MD');p.locator('#hit-kind').select_option('negative');d=p.evaluate('KPHit.getData()');self.assertTrue(all(h['kind']=='negative' and any(r.startswith('MD') for r in h['roles']) for h in d['hits']));self.assertTrue(d['remedies']);p.locator('.hit-remedies-panel > summary').click();expect(p.locator('#hit-remedies .hit-remedy').first).to_be_visible()
  with p.expect_popup() as opened:p.locator('#hit-theory-preview').click()
  preview=opened.value;expect(preview.locator('.hit-report')).to_be_visible();expect(preview.get_by_role('button',name='Zoom +',exact=True)).to_be_visible();pdf=fitz.open(stream=preview.pdf(format='A4',prefer_css_page_size=True),filetype='pdf');text=''.join(page.get_text() for page in pdf);self.assertIn('HIT Remedies',text);self.assertIn('Review directions',text);self.assertNotIn('Sheet1',text);self.assertNotIn('Suicidal',text);pdf.close();preview.close();self.assertEqual(p.evaluate('JSON.stringify(currentKPModel)'),native);self.assertEqual(p.evaluate('KPWesternAspects.getSettings()'),western)
  p.evaluate('KPPreferences.save({...KPPreferences.get(),language:"marathi"})');expect(p.locator('#page-title')).to_have_text('हिट सिद्धांत');expect(p.locator('#hit-theory-preview')).to_contain_text('Preview');self.assertEqual(p.evaluate('KPHit.getData().hits.length'),len(d['hits']))
class HitPrivateTests(unittest.TestCase):
 setUpClass=classmethod(protected.ProtectedServerTests.setUpClass.__func__);tearDownClass=classmethod(protected.ProtectedServerTests.tearDownClass.__func__);setUp=protected.ProtectedServerTests.setUp;tearDown=protected.ProtectedServerTests.tearDown;post=protected.ProtectedServerTests.post;go=protected.ProtectedServerTests.go;private=protected.ProtectedServerTests.private
 def test_private_hit_selectors_and_preview_have_no_engine_code(self):
  self.go('hit-theory');expect(self.page.locator('#hit-results tbody tr').first).to_be_visible();self.assertEqual(self.page.evaluate('typeof KPHitMath'),'undefined');self.page.locator('#hit-level').select_option('AD');expect(self.page.locator('#hit-level')).to_have_value('AD',timeout=30000)
  with self.page.expect_popup() as opened:self.page.locator('#hit-theory-preview').click()
  preview=opened.value;expect(preview.locator('.hit-report')).to_be_visible(timeout=30000);self.assertNotIn('CORRESPONDENCES',preview.content());self.assertNotIn('KPHitMath',preview.content());preview.close();self.assertTrue(self.private('KPHit.getData().hits.every(h=>h.roles.some(r=>r.startsWith("AD")))'))
