/* Browser interface only. Calculations run in the private server worker. */
(()=>{
 let token='',pending=Promise.resolve(),refreshTimer;
 const status=document.createElement('div');status.id='connection-status';status.setAttribute('role','status');
 function notice(message){status.textContent=message;status.style.cssText='position:fixed;bottom:8px;right:8px;background:white;padding:8px;border:1px solid #aaa;z-index:99999';document.body.append(status);}
 async function request(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-KP-Session':token}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});if(!r.ok){const e=await r.json().catch(()=>({error:'Connection failed'}));throw Error(e.error);}return r.json();}
 function show(snapshot){const active=document.activeElement,draft=active?.matches('input,textarea,select')&&!active.readOnly?{value:active.value,checked:active.checked}:null;const focus=active?.dataset.bridgeId,selection=document.activeElement?.selectionStart,scroll=window.scrollY;token=snapshot.token;if(snapshot.download){const bytes=Uint8Array.from(atob(snapshot.download.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes])),link=document.createElement('a');link.href=url;link.download=snapshot.download.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(snapshot.message)notice(snapshot.message);document.getElementById('application-style').textContent=snapshot.css;document.body.className=snapshot.bodyClass;Object.entries(snapshot.bodyData).forEach(([k,v])=>document.body.dataset[k]=v);document.getElementById('application').innerHTML=snapshot.html;const target=focus&&document.querySelector('[data-bridge-id="'+focus+'"]');if(target){if(draft){target.value=draft.value;if(target.type==='checkbox'||target.type==='radio')target.checked=draft.checked;}target.focus({preventScroll:true});try{target.setSelectionRange(selection,selection);}catch(_){}}window.scrollTo(0,scroll);clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(!document.activeElement?.matches('input,textarea,select'))queue(()=>request('/snapshot').then(show));},snapshot.busy?1200:10000);}
 function queue(work){pending=pending.then(work).catch(e=>notice(e.message));return pending;}
 function send(element,kind,extra={}){const id=element?.dataset.bridgeId;if(!id)return;queue(()=>request('/event',{id,kind,...extra}).then(show));}
 async function upload(file){if(!file)return;const text=await file.text();if(text.length>4800000)throw Error('Chart file is too large.');show(await request('/import',{chart:JSON.parse(text)}));}
 document.addEventListener('change',e=>{const el=e.target;if(el.type==='file'){if(el.accept?.includes('image')){queue(async()=>{const file=el.files[0];if(!file)return;if(file.size>3000000)throw Error('Use a photo smaller than 3 MB.');const reader=new FileReader();const photo=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});show(await request('/photo',{photo}));});}else queue(()=>upload(el.files[0]));return;}if(el.matches('input,select,textarea'))send(el,'change',{value:el.value,checked:el.checked});});
 document.addEventListener('click',e=>{const button=e.target.closest('button,[data-bridge-click],a');if(!button)return;if(button.tagName==='A')return;e.preventDefault();if(button.id==='mm-calculate'){const preview=window.open('about:blank','_blank');queue(()=>{if(preview)preview.location.href='/match-preview';});return;}if(button.dataset.clientAction==='export'){location.href='/export';return;}if(button.dataset.clientAction==='print'){window.open('/print','_blank');return;}if(button.dataset.clientAction==='photo'){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.dataset.photoInput='true';document.body.append(input);input.click();return;}if(button.dataset.clientAction==='import'){const input=document.createElement('input');input.type='file';input.accept='.lkp,.json';input.onchange=()=>queue(()=>upload(input.files[0]));input.click();return;}const destructive=/delete|clear form|reset/i.test(button.textContent);const confirmed=destructive?window.confirm('Confirm '+button.textContent.trim()+'?'):false;if(!destructive||confirmed)send(button,'click',{confirmed});});
 document.addEventListener('dblclick',e=>{const row=e.target.closest('[data-bridge-id]');if(row)send(row,'dblclick');});
 document.addEventListener('contextmenu',e=>{const el=e.target.closest('[data-bridge-id]');if(el){e.preventDefault();send(el,'contextmenu',{x:e.clientX,y:e.clientY});}});
 document.addEventListener('toggle',e=>{if(e.target.matches('details')&&e.target.dataset.bridgeOpen!==String(e.target.open)){e.target.dataset.bridgeOpen=String(e.target.open);send(e.target,'toggle',{open:e.target.open});}},true);
 document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input:not([type=file])')){e.target.blur();}});
 queue(()=>request('/snapshot').then(show));
})();
