/* Browser interface only. Calculations run in the private server worker. */
(()=>{
 let token='',pending=Promise.resolve(),refreshTimer;
 const status=document.createElement('div');status.id='connection-status';status.setAttribute('role','status');
 function notice(message){status.textContent=message;status.style.cssText='position:fixed;bottom:8px;right:8px;background:white;padding:8px;border:1px solid #aaa;z-index:99999';document.body.append(status);}
 async function request(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-KP-Session':token}:{},body:data?JSON.stringify(data):undefined,cache:'no-store'});if(!r.ok){const e=await r.json().catch(()=>({error:'Connection failed'}));throw Error(e.error);}return r.json();}
 function show(snapshot){if(snapshot.preferencesConfigured)try{localStorage.setItem('kpProtectedPreferencesV1',JSON.stringify(snapshot.preferences));}catch(_){}const active=document.activeElement,draft=active?.matches('input,textarea,select')&&!active.readOnly?{value:active.value,checked:active.checked}:null;const focus=active?.dataset.bridgeId,selection=document.activeElement?.selectionStart,scroll=window.scrollY;token=snapshot.token;if(snapshot.download){const bytes=Uint8Array.from(atob(snapshot.download.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes])),link=document.createElement('a');link.href=url;link.download=snapshot.download.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(snapshot.message)notice(snapshot.message);document.getElementById('application-style').textContent=snapshot.css;document.body.className=snapshot.bodyClass;document.documentElement.lang=snapshot.language||'en';document.documentElement.dataset.kpLanguage=snapshot.preferences?.language||'english';Object.entries(snapshot.bodyData).forEach(([k,v])=>document.body.dataset[k]=v);document.getElementById('application').innerHTML=snapshot.html;const target=focus&&document.querySelector('[data-bridge-id="'+focus+'"]');if(target){if(draft){target.value=draft.value;if(target.type==='checkbox'||target.type==='radio')target.checked=draft.checked;}target.focus({preventScroll:true});try{target.setSelectionRange(selection,selection);}catch(_){}}window.scrollTo(0,scroll);clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{if(!document.activeElement?.matches('input,textarea,select'))queue(()=>request('/snapshot').then(show));},snapshot.busy?1200:10000);}
 function queue(work){pending=pending.then(work).catch(e=>notice(e.message));return pending;}
 function send(element,kind,extra={}){const id=element?.dataset.bridgeId;if(!id)return;queue(()=>request('/event',{id,kind,...extra}).then(show));}
 async function upload(file){if(!file)return;const text=await file.text();if(text.length>4800000)throw Error('Chart file is too large.');show(await request('/import',{chart:JSON.parse(text)}));}
 document.addEventListener('change',e=>{const el=e.target;if(el.type==='file'){if(el.accept?.includes('image')){queue(async()=>{const file=el.files[0];if(!file)return;if(file.size>3000000)throw Error('Use a photo smaller than 3 MB.');const reader=new FileReader();const photo=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});show(await request('/photo',{photo}));});}else queue(()=>upload(el.files[0]));return;}if(el.matches('input,select,textarea'))send(el,'change',{value:el.value,checked:el.checked});});
 document.addEventListener('click',e=>{const button=e.target.closest('button,[data-bridge-click],a');if(!button)return;if(button.tagName==='A')return;e.preventDefault();if(['am-preview','am-print','am-pdf','south-single-page-preview','south-single-page-print','home-single-page-preview','home-single-page-print'].includes(button.id)){if(button.id==='am-pdf'){const a=document.createElement('a');a.href='/aspects-pdf';a.download='KP-Western-Aspects.pdf';queue(()=>a.click());return;}const route=button.id.startsWith('am-')?(button.id==='am-print'?'/aspects-print':'/aspects-preview'):(button.id.endsWith('-print')?'/single-page-print':'/single-page-preview');const preview=window.open('about:blank','_blank');queue(()=>{if(preview)preview.location.href=route;});return;}if(['transit-preview','transit-chart-preview','transit-panchang-preview','ephemeris-preview','event-promise-preview','education-profession-preview','disease-preview','dasha-promise-preview','significators-preview','nadi-astrology-preview','south9-preview'].includes(button.id)){const preview=window.open('about:blank','_blank');queue(()=>{if(preview)preview.location.href='/'+button.id;});return;}if(/^pc-(natal|horary)-(save|open)$/.test(button.id)){if(button.id.endsWith('-open')){KPChartFiles.open().then(file=>queue(async()=>{if(!file)return;await upload(file);await request('/event',{id:document.querySelector('[data-tab="south9"]').dataset.bridgeId,kind:'click'}).then(show);})).catch(e=>notice(e.name==='AbortError'?'Open cancelled.':e.message));}else{KPChartFiles.directory().then(target=>queue(async()=>{await request('/event',{id:button.dataset.bridgeId,kind:'click'}).then(show);const r=await fetch('/export');if(!r.ok)throw Error('Chart export failed');notice(await KPChartFiles.save(await r.json(),target));})).catch(e=>notice(e.name==='AbortError'?'Save cancelled.':e.message));}return;}if(button.id==='mm-calculate'){const preview=window.open('about:blank','_blank');queue(()=>{if(preview)preview.location.href='/match-preview';});return;}if(button.dataset.clientAction==='export'){location.href='/export';return;}if(button.dataset.clientAction==='print'){window.open('/print','_blank');return;}if(button.dataset.clientAction==='photo'){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.dataset.photoInput='true';document.body.append(input);input.click();return;}if(button.dataset.clientAction==='import'){const input=document.createElement('input');input.type='file';input.accept='.lkp,.json';input.onchange=()=>queue(()=>upload(input.files[0]));input.click();return;}const destructive=/delete|clear form|reset/i.test(button.textContent);const confirmed=destructive?window.confirm('Confirm '+button.textContent.trim()+'?'):false;if(!destructive||confirmed)send(button,'click',{confirmed});});
 document.addEventListener('dblclick',e=>{const row=e.target.closest('[data-bridge-id]');if(row)send(row,'dblclick');});
 document.addEventListener('contextmenu',e=>{const el=e.target.closest('[data-bridge-id]');if(el){e.preventDefault();send(el,'contextmenu',{x:e.clientX,y:e.clientY});}});
 document.addEventListener('toggle',e=>{if(e.target.matches('details')&&e.target.dataset.bridgeOpen!==String(e.target.open)){e.target.dataset.bridgeOpen=String(e.target.open);send(e.target,'toggle',{open:e.target.open});}},true);
 document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input:not([type=file])')){e.target.blur();}});
 let clockBusy=false;
 setInterval(()=>{const n=document.getElementById('ruling-clock'),time=document.getElementById('ruling-clock-time');if(time&&n)time.textContent=new Date(Date.now()+Number(n.dataset.timezone||5.5)*3600000).toISOString().replace('T',' · ').slice(0,21);},1000);
 setInterval(async()=>{if(clockBusy||!token||!document.getElementById('ruling-clock'))return;clockBusy=true;try{const d=await request('/ruling-clock');const n=document.getElementById('ruling-clock');if(n){n.dataset.timezone=String(d.timezone);document.getElementById('ruling-clock-place').textContent='RP · '+d.place;document.getElementById('ruling-clock-lords').textContent='Asc '+[d.asc.sgl,d.asc.stl,d.asc.sl,d.asc.ssl].join('/')+' · Moon '+[d.moon.sgl,d.moon.stl,d.moon.sl,d.moon.ssl].join('/')+' · Day '+d.dayLord+' · Hour '+d.hourLord;}}catch(_){}finally{clockBusy=false;}},10000);
 queue(async()=>{let saved;try{saved=JSON.parse(localStorage.getItem('kpProtectedPreferencesV1')||'null');}catch(_){}show(await request('/snapshot'));if(saved&&typeof saved==='object')show(await request('/preferences',{settings:saved}));});
})();

(()=>{'use strict';let folder;const db=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('KPChartFolder',1);r.onupgradeneeded=()=>r.result.createObjectStore('folders');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});async function stored(value){const d=await db();return new Promise((resolve,reject)=>{const t=d.transaction('folders',value?'readwrite':'readonly'),r=value?t.objectStore('folders').put(value,'kundali'):t.objectStore('folders').get('kundali');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);t.oncomplete=()=>d.close();});}
async function directory(){if(!window.showDirectoryPicker)return null;if(!folder)try{folder=await stored();}catch(_){}if(folder){let permission=await folder.queryPermission({mode:'readwrite'});if(permission!=='granted')permission=await folder.requestPermission({mode:'readwrite'});if(permission==='granted')return folder;folder=null;}const parent=await window.showDirectoryPicker({mode:'readwrite',id:'kp-kundali-folder'});folder=await parent.getDirectoryHandle('KP Raphael',{create:true});try{await stored(folder);}catch(_){}return folder;}
function name(chart){const f=chart.fields||{},clean=String(f.name?.value||'kundali').replace(/[^\p{L}\p{N}_-]+/gu,'-').slice(0,65);return clean+'-'+(f['chart-kind']?.value||'natal')+'-'+new Date().toISOString().replace(/[:.]/g,'-')+'.lkp';}
async function save(chart,target){const text=JSON.stringify(chart,null,2),filename=name(chart);if(target){const file=await target.getFileHandle(filename,{create:true}),write=await file.createWritable();await write.write(text);await write.close();return 'Saved '+filename+' in KP Raphael.';}const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return 'Downloaded '+filename+'. Folder saving requires a browser with folder access.';}
async function open(){if(window.showOpenFilePicker){const [handle]=await window.showOpenFilePicker({multiple:false,startIn:folder||'documents',types:[{description:'KP Kundali',accept:{'application/json':['.lkp']}}]});return handle.getFile();}return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='.lkp';input.hidden=true;document.body.append(input);input.addEventListener('change',e=>{e.stopPropagation();resolve(input.files[0]||null);input.remove();},{once:true});input.addEventListener('cancel',()=>{resolve(null);input.remove();},{once:true});input.click();});}
window.KPChartFiles=Object.freeze({directory,save,open});})();
