/* Presentation tools only: drawings and tab zoom never change chart calculations. */
(()=>{'use strict';
const NS='http://www.w3.org/2000/svg',tabs=new Map();let panel,canvas,target,draft=null,drag=null,visible=false,tool='pointer',colour='#c62828',width=3,queued=false;
const $=id=>panel?.querySelector('#teach-'+id),active=()=>document.querySelector('.tab.active:not(#tutorial)'),node=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n;};
function state(){if(!target)return null;if(!tabs.has(target.id))tabs.set(target.id,{drawings:[],undo:[],redo:[],zoom:1});return tabs.get(target.id);}
function history(){const s=state();s.undo.push(JSON.stringify(s.drawings));if(s.undo.length>60)s.undo.shift();s.redo=[];}
function shape(d,index){const attrs={stroke:d.colour,'stroke-width':d.tool==='marker'?d.width*5:d.width,fill:'none','stroke-linecap':'round','stroke-linejoin':'round','data-teaching-drawing':index},a=d.points[0],z=d.points[d.points.length-1];let n;
 if(d.tool==='text'){n=node('text',{x:a[0],y:a[1],fill:d.colour,stroke:'none','font-size':12+d.width*2,'font-family':'Arial, Mangal, sans-serif','data-teaching-drawing':index});n.textContent=d.text;}
 else if(['pen','marker'].includes(d.tool)){n=node('path',{...attrs,d:d.points.length===1?'M'+a.join(' ')+'l.1 .1':d.points.map((p,i)=>(i?'L':'M')+p.join(' ')).join(' ')});if(d.tool==='marker')n.setAttribute('opacity','.32');}
 else if(['line','arrow'].includes(d.tool)){n=node('line',{...attrs,x1:a[0],y1:a[1],x2:z[0],y2:z[1]});if(d.tool==='arrow')n.setAttribute('marker-end','url(#teach-arrowhead)');}
 else if(d.tool==='rect')n=node('rect',{...attrs,x:Math.min(a[0],z[0]),y:Math.min(a[1],z[1]),width:Math.abs(z[0]-a[0]),height:Math.abs(z[1]-a[1])});
 else n=node('ellipse',{...attrs,cx:(a[0]+z[0])/2,cy:(a[1]+z[1])/2,rx:Math.abs(z[0]-a[0])/2,ry:Math.abs(z[1]-a[1])/2});return n;
}
function draw(){if(!canvas||!target)return;const s=state(),defs=node('defs'),arrow=node('marker',{id:'teach-arrowhead',viewBox:'0 0 10 10',refX:8,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'});arrow.append(node('path',{d:'M0 0L10 5L0 10Z',fill:'context-stroke'}));defs.append(arrow);canvas.replaceChildren(defs,...s.drawings.map(shape));if(draft)canvas.append(shape(draft,'draft'));canvas.style.pointerEvents=visible&&tool!=='pointer'?'auto':'none';canvas.hidden=!visible;$('undo').disabled=!s.undo.length;$('redo').disabled=!s.redo.length;$('zoom-label').textContent=Math.round(s.zoom*100)+'%';$('clear').disabled=!s.drawings.length;}
function size(){if(!target||!canvas)return;const w=Math.max(1,target.clientWidth),h=Math.max(1,target.clientHeight);canvas.setAttribute('viewBox','0 0 '+w+' '+h);canvas.style.width=w+'px';canvas.style.height=h+'px';}
function point(e){const r=canvas.getBoundingClientRect(),box=canvas.viewBox.baseVal;return [Math.max(0,Math.min(box.width,(e.clientX-r.left)/r.width*box.width)),Math.max(0,Math.min(box.height,(e.clientY-r.top)/r.height*box.height))];}
function commit(){if(!draft)return;history();state().drawings.push(draft);draft=null;draw();}
function pointerDown(e){if(e.button!==0||!visible||tool==='pointer')return;e.preventDefault();if(tool==='eraser'){const n=e.target.closest('[data-teaching-drawing]');if(n){history();state().drawings.splice(Number(n.dataset.teachingDrawing),1);draw();}return;}if(state().drawings.length>=200){$('clear').focus();return;}draft={tool,colour,width,points:[point(e)]};if(tool==='text'){const text=$('label').value.trim().slice(0,240);if(!text){draft=null;$('label').focus();return;}draft.text=text;commit();return;}canvas.setPointerCapture(e.pointerId);draw();}
function pointerMove(e){if(!draft)return;const p=point(e);if(['pen','marker'].includes(draft.tool)){if(draft.points.length<1000)draft.points.push(p);}else draft.points=[draft.points[0],p];draw();}
function zoom(change){if(!target)return;const s=state();s.zoom=change===0?1:Math.max(.5,Math.min(2,Math.round((s.zoom+change)*10)/10));target.style.zoom=String(s.zoom);requestAnimationFrame(()=>{size();draw();});}
const css=`#kp-teaching-tools{position:fixed;right:12px;bottom:12px;z-index:100010;width:600px;max-width:calc(100vw - 24px);box-sizing:border-box;background:#fffef0;color:#172033;border:1px solid #91accc;border-radius:7px;box-shadow:0 4px 18px #24344c35;padding:10px;font:13px/1.4 Arial,Mangal,sans-serif;touch-action:none}#kp-teaching-tools[hidden]{display:none!important}#kp-teaching-tools .teach-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin:0 0 8px}#kp-teaching-tools .teach-row:last-child{margin-bottom:0}#kp-teaching-tools label{display:flex;align-items:center;gap:5px;width:auto;margin:0;font-size:13px;font-weight:400;color:inherit}#kp-teaching-tools :is(input,select,button){box-sizing:border-box;margin:0;font:12px Arial,Mangal,sans-serif;border:1px solid #abc1dc;border-radius:5px;min-height:30px;color:#173a60;background:#f3f7ff}#kp-teaching-tools select{padding:4px;width:auto}#kp-teaching-tools button{padding:5px 10px;cursor:pointer}#kp-teaching-tools button:disabled{color:#8195aa;background:#f5f7fa;cursor:default}#kp-teaching-tools input[type=color]{width:36px;height:32px;padding:3px}#kp-teaching-tools .teach-text{flex:1}#kp-teaching-tools input[type=text]{width:100%;padding:5px;min-width:0;background:white}#kp-teaching-tools .teach-label-row{flex-wrap:nowrap}.kp-teach-canvas{position:absolute;left:0;top:0;z-index:40;touch-action:none;overflow:visible}.kp-teach-canvas[hidden]{display:none!important}body[data-kp-theme-type=dark] #kp-teaching-tools{background:#223246;color:#edf5ff;border-color:#6684a5}body[data-kp-theme-type=dark] #kp-teaching-tools :is(input,select,button){background:#30465f;color:#edf5ff;border-color:#7493b4}body[data-kp-theme-type=dark] #kp-teaching-tools button:disabled{color:#a6b6ca;background:#293a50}@media print{#kp-teaching-tools,.kp-teach-canvas{display:none!important}}`;
function mount(){if(panel?.isConnected)return;document.querySelectorAll('#kp-teaching-tools').forEach(n=>n.remove());panel=document.createElement('aside');panel.id='kp-teaching-tools';panel.dataset.localTutorial='true';panel.dataset.noLocalize='';panel.setAttribute('aria-label','Teaching tools · अध्यापन साधने');panel.title='TUT shows or hides these tools. Drag the toolbar background to move it. Pointer lets you use the software controls.';panel.hidden=!visible;
 panel.innerHTML='<div class="teach-row"><label>Tool <select id="teach-tool"><option value="pointer">Pointer · निवड</option><option value="pen">Pen · लेखणी</option><option value="marker">Highlighter · ठळक</option><option value="line">Line · रेषा</option><option value="arrow">Arrow · बाण</option><option value="rect">Rectangle · चौकट</option><option value="ellipse">Circle / ellipse · वर्तुळ</option><option value="text">Text label · मजकूर</option><option value="eraser">Eraser · पुसा</option></select></label><label>Colour <input id="teach-colour" type="color" value="#c62828"></label><label>Size <select id="teach-width">'+[1,2,3,5,8,12].map(n=>'<option value="'+n+'"'+(n===3?' selected':'')+'>'+n+'</option>').join('')+'</select></label><button id="teach-undo" type="button">Undo</button><button id="teach-redo" type="button">Redo</button><button id="teach-clear" type="button">Clear</button></div><div class="teach-row teach-label-row"><label for="teach-label">Text label</label><input class="teach-text" id="teach-label" type="text" maxlength="240" placeholder="Enter an explanation, choose Text, then click the page"></div><div class="teach-row"><button id="teach-zoom-in" type="button">Zoom +</button><button id="teach-zoom-out" type="button">Zoom −</button><button id="teach-fit" type="button">Fit</button><span id="teach-zoom-label">100%</span></div>';document.body.append(panel);
 $('tool').value=tool;$('colour').value=colour;$('width').value=String(width);$('tool').addEventListener('change',()=>{tool=$('tool').value;draft=null;draw();});$('colour').addEventListener('change',()=>colour=$('colour').value);$('width').addEventListener('change',()=>width=Number($('width').value));
 $('undo').addEventListener('click',()=>{const s=state();if(s?.undo.length){s.redo.push(JSON.stringify(s.drawings));s.drawings=JSON.parse(s.undo.pop());draw();}});$('redo').addEventListener('click',()=>{const s=state();if(s?.redo.length){s.undo.push(JSON.stringify(s.drawings));s.drawings=JSON.parse(s.redo.pop());draw();}});$('clear').addEventListener('click',()=>{if(state()?.drawings.length){history();state().drawings=[];draw();}});$('zoom-in').addEventListener('click',()=>zoom(.1));$('zoom-out').addEventListener('click',()=>zoom(-.1));$('fit').addEventListener('click',()=>zoom(0));
 panel.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,select'))return;const r=panel.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};panel.setPointerCapture(e.pointerId);});panel.addEventListener('pointermove',e=>{if(!drag)return;const r=panel.getBoundingClientRect();panel.style.left=Math.max(0,Math.min(innerWidth-r.width,e.clientX-drag.x))+'px';panel.style.top=Math.max(0,Math.min(innerHeight-r.height,e.clientY-drag.y))+'px';panel.style.right='auto';panel.style.bottom='auto';});panel.addEventListener('pointerup',()=>drag=null);panel.addEventListener('pointercancel',()=>drag=null);
}
let resizeObserver;
function install(){mount();if(!document.getElementById('kp-teaching-tools-style')){const style=document.createElement('style');style.id='kp-teaching-tools-style';style.textContent=css;document.head.append(style);}const next=active();if(!next)return;
 if(next!==target||!canvas?.isConnected){draft=null;canvas?.remove();resizeObserver?.disconnect();target=next;if(getComputedStyle(target).position==='static')target.style.position='relative';target.style.zoom=String(state().zoom);canvas=node('svg',{class:'kp-teach-canvas no-print','aria-label':'Annotations for '+target.id,role:'img'});canvas.dataset.noLocalize='';target.append(canvas);canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',commit);canvas.addEventListener('pointercancel',()=>{draft=null;draw();});resizeObserver=new ResizeObserver(()=>size());resizeObserver.observe(target);}
 size();draw();document.querySelectorAll('#quick-tutorial,[data-tab="tutorial"]').forEach(b=>{b.setAttribute('aria-expanded',String(visible));b.title='TUT · Teaching tools on the current tab';});
}
function toggle(){visible=!visible;install();panel.hidden=!visible;draw();}
window.KPTutorial=Object.freeze({install,toggle,refresh:install,getState:()=>({visible,tool,colour,width,tab:target?.id,zoom:state()?.zoom||1,annotations:JSON.parse(JSON.stringify(state()?.drawings||[]))})});
function init(){install();document.addEventListener('click',e=>{if(e.target.closest('#quick-tutorial,[data-tab="tutorial"]')){e.preventDefault();e.stopImmediatePropagation();toggle();}},true);new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install();});}).observe(document.body,{attributes:true,subtree:true,attributeFilter:['class']});window.addEventListener('resize',()=>{size();if(panel){const r=panel.getBoundingClientRect();if(r.right>innerWidth||r.bottom>innerHeight){panel.style.left='auto';panel.style.top='auto';panel.style.right='12px';panel.style.bottom='12px';}}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
